Crypto_project/urls.py
from django.contrib import admin

from django.urls import include, path

from classroom.views import classroom, students, teachers

from django.conf.urls.static import static

from django.conf import settings


urlpatterns = [
    path('', include('classroom.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

classroom/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('readys2/<int:pk>/',teachers.readys_deleguer, name='readysD'),
    path('readys/<int:pk>/',teachers.readys_responsable, name='readysR'),
    path('ready/<int:pk>/',classroom.ready, name='ready'),
    path('success', classroom.success, name='succ'),
    path('error', classroom.error, name='err'),
    path('frm', teachers.StandardForm, name='StandardForm'),
    path('services', classroom.home2, name='home2'),
    path('', classroom.get_code, name='home'),
    path('media/',classroom.doc_view,name='aff_docs'),
    path('informations/<int:pk>',classroom.index,name='inf'),
    path('debloquer/<int:pk>',classroom.index2,name='inf2'),
    path('resp/<int:pk>/',teachers.responses_vue,name='aff_rep'),
    path('cp',teachers.responses_vue2,name='cp'),
    path('resp2/<int:pk>/',teachers.responses_vue3,name='aff_rep2'),
    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),

    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'classroom'), namespace='teachers')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

classroom/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from ..models import Documment
from django.shortcuts import render
from django.template import Context

from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from smartcard.System import readers 
from smartcard.util import toHexString
from ..forms import VerifForm


global connection
global reponse
reponse = 0


def index2(request,pk):
  #AID du package et applet
  SELECT_APPLIC = [0x00,0xA4,0x04,0x00,0x05,0x11,0x11,0x11,0x11,0x11]
  SELECT_APPLET = [0x00,0xA4,0x04,0x00,0x06,0x11,0x11,0x11,0x11,0x11,0x00]
  #etape 1 : selectionner le package et l applet
  cnx = selection(SELECT_APPLIC,SELECT_APPLET)
  if cnx == 1:
    val_champ = pk
    c = debloquer(val_champ)
    if c == 1:
      msg2 = "la carte a été débloqué"
      cnt2 = {
        'msg' : msg2,
      }
      return render(request, "success.html", cnt2)
    elif c == 3:
      msg = "carte bloqué"
      cnt = {
       'msg' : msg,
      }
      return render(request, "error.html", cnt2)
    else :
      msg = "il vous reste "+ str(c)
      cnt = {
       'msg' : msg,
      }
      return render(request,'error.html',cnt)
  else:
    return HttpResponse("erreur inserez votre carte")


def index(request,pk):
  #AID du package et applet
  SELECT_APPLIC = [0x00,0xA4,0x04,0x00,0x05,0x11,0x11,0x11,0x11,0x11]
  SELECT_APPLET = [0x00,0xA4,0x04,0x00,0x06,0x11,0x11,0x11,0x11,0x11,0x00]
  #etape 1 : selectionner le package et l applet
  cnx = selection(SELECT_APPLIC,SELECT_APPLET)
  if cnx == 1:
    #on ecrit sur la carte a chaque fois car on est en simulation 
    

    # 
    # 
    #lire les donnees stockees dans la carte
    

    val_champ = pk
    rep = verify(val_champ,0)
    if rep == ['90','0'] :
      dic = Ecrire_info({0x01:"KASBADJI",0x02:"161631097303",0x03:"Sofian",0x04:"01-03-1999",0x05:"sofian"})
      # dic = Ecrire_info({0x01:"Enseignant1",0x02:"-",0x03:"prenom1",0x04:"01-05-1964",0x05:"Pr_Crypto"})
      # dic = Ecrire_info({0x01:"Enseignant2",0x02:"-",0x03:"prenom2",0x04:"01-05-1978",0x05:"Pr_secR"})
      # dic = Ecrire_info({0x01:"SEBAA",0x02:"161631097203",0x03:"Lina",0x04:"27-10-1998",0x05:"lina"})
      # dic = Ecrire_info({0x01:"ZAKARIA",0x02:"161631096205",0x03:"Lamia",0x04:"28-10-1998",0x05:"lamia"})
      # dic = Ecrire_info({0x01:"AHDIBI",0x02:"161631097297",0x03:"Aymen",0x04:"01-09-1999",0x05:"aymen"})
      # dic = Ecrire_info({0x01:"ZEMMOURI",0x02:"161631096200",0x03:"Lila",0x04:"01-05-1999",0x05:"lila"})
      liste_data = lire_info([0x10,0x21,0x31,0x40,0x0b])
      #recuperer username et password
      username = liste_data[4]
      password = val_champ
      user = authenticate(request,username=username, password=password)
      if user is not None:
        login(request,user)
        if request.user.is_authenticated:
          if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
          else:
            return redirect('students:quiz_list')
        else:
          return render(request,'error.html',)
    elif rep == ['68','1'] or rep == ['68','2']:
      rep = str(rep[-1])
      msg = "il vous reste "+ rep
      cnt = {
       'msg' : msg,
      }
      return render(request,'error.html',cnt)
      #return HttpResponse("il vous reste "+rep)
    elif rep == ['69','82']:
      msg = "carte bloqué"
      cnt = {
       'msg' : msg,
      }
      return render(request,'error.html',cnt)
      #return HttpResponse("carte bloquee")
# ---------------------------debloquer la carte ------------------------------
    # val_champ = pk
    # c = debloquer(val_champ)
    # if c == 1:
      # return HttpResponse("carte deblouquee")
    # elif c == 3:
      # return HttpResponse("carte bloquee")
    # else :
     # return HttpResponse("mot des passe incorrecte il vous reste"+str(c))
# -----------------------------------------------------------------------------
  else:
    return render(request,'error.html',)


def selection(SELECT_APPLIC,SELECT_APPLET):
 global connection
 global reponse
 
 try:
  r=readers()
  print(r)
  connection = r[0].createConnection()
  connection.connect()
  reponse =1
  print(reponse)
  try:
   data, sw1, sw2 = connection.transmit(SELECT_APPLIC)
   sw1 = "%x"%sw1
   sw2 = "%x"%sw2
 
   if ((sw1=="90") and (sw2 == "0")):
    data, sw1, sw2 = connection.transmit(SELECT_APPLET)
    sw1 = "%x"%sw1
    sw2 = "%x"%sw2
    # verifier la reponse de selection de l'applet
    if ((sw1=="90") and (sw2 == "0")):
     return 1
  except:
   return 0
 except:
  return 0


def Ecrire_info(dic):
 global reponse
 global connection
 if reponse ==1:
  # SEND_ECRIR = [CLA, INS, P1, P2, LC, DATA_FIELD]
  for i in dic:
   liste = []
   donnee = str(dic[i])
   long = len(donnee)

   for x in range(long):
    liste.append(ord(donnee[x]))

   SEND_ECRIR = [176,i,0,0,len(liste)]
   for i in liste:
    SEND_ECRIR.append(i)
   dat,sw1, sw2 = connection.transmit(SEND_ECRIR)


def lire_info(liste):
 global reponse
 global connection
 donnee = ''
 if reponse ==1:
  listedonnee = []
  for i in liste: # i cest l INS 
   # SEND_LIRE = [CLA, INS, P1, P2, Le] en entier
   SEND_LIRE = [176,i,0,0] 
   data, sw1, sw2 = connection.transmit(SEND_LIRE)
   sw1 = "%x"%sw1
   sw2 = "%x"%sw2
   # print(data)
   #verifier si l action est bien passee
   if ((sw1=="90")  and (sw2 == "0")):
    # data est une liste
    donnee =''
    liste =[]
   for i in range(len(data)):
    if (data[i] != 0): #pour eviter l'affichage les case vide (/x00) 
     liste.append(chr(data[i]))
     donnee =donnee+liste[i]
   listedonnee.append(donnee)
  return listedonnee




class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

def home2(request):
  if request.user.is_authenticated:
    if request.user.is_teacher:
      return render(request,'services.html')
    else:
      return redirect('students:quiz_list')
  return render(request,'classroom/home.html',)

def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        else:
            return redirect('students:quiz_list')
    return render(request, 'classroom/home.html')

def home3(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        else:
            return redirect('students:quiz_list')
    return render(request, 'classroom/home2.html')


def doc_view(request):
    if request.user.is_authenticated:
        documents = Documment.objects.all()
        p = "http://localhost:8000/"
    else:
        documents = []
    args = {
    'documents': documents,
    'p' : p
    }
    return render(request,'doc.html', args)


def error(request):
   return render(request,'error.html',)

def success(request):
   return render(request,'success.html',)

def ready(request,pk):
  quiz = Quiz.objects.filter(id = pk)
  quiz.results_ready +=1
  quiz.save()

  return redirect(request, './',)


def get_code(request):
  global reponse
  global connection
  if request.user.is_authenticated:
    if request.user.is_teacher:
      return redirect('teachers:quiz_change_list')
    else:
      return redirect('students:quiz_list')

  elif request.method == 'POST':
    form = VerifForm(request.POST)
    if form.is_valid():
      code = form.cleaned_data['your_code']
      print(code)
      cnt = {
        'code' : code,
      }
      return render(request,'classroom/home2.html', cnt)
  else:
    form = VerifForm()

  return render(request, 'classroom/home.html',{'form': form})


def verify(val_champ,user):
 global reponse
 global connection
 # SEND_VERIFY = [176,20,user,0,4]
 donnee = str(val_champ)
 liste = []
 long = len(donnee)

 for x in range(4):
    liste.append(ord(donnee[x]))

 SEND_VERIFY = [176,0x20,user,0,4]
 for i in liste:
    SEND_VERIFY.append(i)
 dat,sw1, sw2 = connection.transmit(SEND_VERIFY)
 

 sw1 = "%x"%sw1
 sw2 = "%x"%sw2
 rep = [sw1,sw2]
 return rep

def debloquer(val_champ):
  rep = verify(val_champ,1)
  if rep == ['90','0'] :
   # success
   SEND_DEBLOK = [176,0x07,0,0,4,0x31,0x32,0x33,0x34]
   connection.transmit(SEND_DEBLOK)
   return 1
  elif rep == ['68','1'] or rep == ['68','2']:
    rep = str(rep[-1])
    return rep
  elif rep == ['69','82']:
    return 3

classroom/views/students.py
import util.crypto as c
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, TakeQuizForm
from ..models import Quiz, Student, TakenQuiz, User, Answer, Question, Teacher
from datetime import date





class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:quiz_list')


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/students/quiz_list.html'

    def get_queryset(self):
        today = date.today()
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(subject__in=student_interests) \
            .exclude(pk__in=taken_quizzes) \
            .exclude(date_fin__lt = today ) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0) 
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'classroom/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset



@login_required
@student_required
def take_quiz(request, pk):
    today = date.today()
    quiz = get_object_or_404(Quiz, pk=pk)
    if (quiz.date_fin < today):
        return render(request, 'error.html',)
    else:

        q = Question.objects.filter(quiz_id=quiz.id)
        student = request.user.student

        if student.quizzes.filter(pk=pk).exists():
            return render(request, 'students/taken_quiz.html')

        total_questions = quiz.questions.count()
        unanswered_questions = student.get_unanswered_questions(quiz)
        total_unanswered_questions = unanswered_questions.count()
        progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
        question = unanswered_questions.first()

        if request.method == 'POST':
            form = TakeQuizForm(question=question, data=request.POST)
            if form.is_valid():
                with transaction.atomic():
                    
                    student_answer = form.save(commit=False)
                    student_answer.student = student
                    student_answer.quiz = quiz
                    student_answer.question = question
                    # recuperer la réponse de l'etudiant
                    answer_ch = Answer.objects.filter(id = request.POST['answer'])[0]
                    # récuperer la clé de chiffrement
                    name = quiz.name+"_"+quiz.subject.specialite+"_"+quiz.subject.section
                    public_key = c.get_pub_key(name)
                   
                    # crypter la réponse
                    answer_ch = c.crypter_msg(answer_ch.text, public_key )
                    student_answer.answer = answer_ch
                    student_answer.save()
                    if student.get_unanswered_questions(quiz).exists():
                       
                        return redirect('students:take_quiz', pk)
                    else:
                        TakenQuiz.objects.create(student=student, quiz=quiz, score=0.0)
                        return redirect('students:quiz_list')
        else:
            form = TakeQuizForm(question=question)

        return render(request, 'classroom/students/take_quiz_form.html', {
            'quiz': quiz,
            'question': question,
            'form': form,
            'progress': progress,
        })



def update_project_filter(request):
    selected_project_id = project_form.cleaned_data["Project_Name"].id
    request.session['selected_project_id'] = selected_project_id

def update_project(request):
    selected_project_id = request.session.get('selected_project_id')

classroom/templates/classroom/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">Mes formulaires</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Ajouter une nouvelle question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Ajouter une nouvelle question</h2>
  <p class="lead">Premierement ecrivez votre question. Dans la procheine etape vous pourrez ajouter les reponses possible.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Sauvegarder</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Ignorer</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">Mes formulaires</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row"> 
          <div class="col-2">
            <strong>Supprimer?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Votre question peut avoir au moin <strong>2</strong> reponses et au maximum  <strong>10</strong> reponses. S'lectionnez au moin une reponses.</small>
    </p>
    <button type="submit" class="btn btn-success">Sauvegarder</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Ignorer</a>
    <a href="{% url 'teachers:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">Supprimer</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">Mesformulaires</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirmer suppression</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confimer suppression</h2>
  <p class="lead">Vous etes sure de supprimer la question <strong>"{{ question.text }}"</strong>?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Oui, je suis sure</button>
    <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Ignorer</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/quiz_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">Mes formulaires</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary float-right">Voir Resultats</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Sauvegarder changements</button>
        <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Ignorer</a>
        <a href="{% url 'teachers:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">Supprimer</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Reponses</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">Pas de question creer encore , allez-sy <a href="{% url 'teachers:question_add' quiz.pk %}">Ajouter la premiere question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'teachers:question_add' quiz.pk %}" class="btn btn-primary btn-sm">Ajouter question</a>
    </div>
  </div>
{% endblock %}

classroom/templates/classroom/teachers/quiz_change_list.html
{% extends 'base.html' %}

{% block content %}
{% if user.teacher.is_responsable %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Mes CP</li>
    </ol>
  </nav>
  <p>
    <h2>Création</h2>
  <div class="w3-container">  
    <div class="w3-light-grey">
      <div id="myBar" class="w3-blue" style="height: 24px;width: 0"></div>
    </div><br>
    <a href="{% url 'StandardForm' %}"  onclick="move()" class="btn btn-secondary mb-3" role="button">CP standard</a><!---->
    <a href="{% url 'teachers:quiz_add' %}" class="btn btn-info mb-3" role="button">CP personnalisé</a>
    </p>
  </div>
  <h2 class="mb-3">Mes Formulaires</h2>

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Formulaires</th>
          <th>Specialité</th>
          <th>Questions</th>
          <th>Pris</th>
          <th>date fin</th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="align-middle">{{ quiz.date_fin }}</td>
            <td class="text-right">
            {% if quiz.date_fin < today %}
              <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary">Voir Resultats</a>
            {%else%}
              <a  class="btn btn-warning">CP en cours...</a>          
            {% endif %}  
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">Vous avez creer aucun formulaire encore.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
<table class="table mb-0">
      <thead>
        <tr>
          <th>Formulaires</th>
          <th>Specialité</th>
          <th>date fin</th>
          <th>responsable</th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizs %}
          <tr>
            <td class="align-middle"><a>{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.date_fin }}</td>
            <td class="align-middle">{{ quiz.owner }}</td>
            <td class="text-right">
            {% if quiz.date_fin < today %}
              <a  class="btn btn-primary">CP terminé</a>
            {% else %}
              <a class="btn btn-warning">CP en cours...</a>
            {% endif %} 
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">Vous avez creer aucun formulaire encore.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% endif %}
{% endblock %}